# Generated by Django 2.1.7 on 2019-03-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190302_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='pet_ptr',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='pet_ptr',
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(default='Dog', max_length=255),
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
